name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ssak
            asset_name: ssak-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ssak
            asset_name: ssak-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ssak
            asset_name: ssak-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ssak.exe
            asset_name: ssak-windows-x86_64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build (release)
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
